config/routes.rb
Rails.application.routes.draw do
  root to: 'sentences#index'

  resources :sentences, only: %i{index new create}
end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  validates :text, presence: true

  def say
    spawn('say', '-v', 'kyoko', text)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  def index
    @sentences = Sentence.order(created_at: :desc).first(10)
  end

  def new
    @sentence = Sentence.new
  end

  def create
    @sentence = Sentence.new(sentence_params)
    if @sentence.save
      @sentence.say
      flash[:notice] = 'successfully created'
      redirect_to sentences_path
    else
      flash.now[:error] = @sentence.errors.full_messages.join(' ')
      render :new
    end
  end

  private

  def sentence_params
    params.require(:sentence).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Shovel
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .notice
      - if flash[:error].present?
        = flash[:error]
      - elsif flash[:notice].present?
        = flash[:notice]
    = yield

app/views/sentences/index.html.haml
- @sentences.each do |sentence|
  = sentence.text
  %br

.link
  = link_to 'New', new_sentence_path

app/views/sentences/new.html.haml
= form_for @sentence do |f|
  = f.text_field :text
  = f.submit